--PRACTICA 9
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 29/04/22
--DESCRIPCION: Practicar la restauración de backups y headers de bd superherores

--RESTAURAR PRIMER RESPALDO DE SUPERHEROES
USE master

--A) RESTAURA EL HEADER DEL PRIMER BACKUP COMPLETO SUPERHEROES QUE REALIZASTE.
RESTORE HEADERONLY
FROM DISK = 'C:\ABD2022\U4\RespaldoFull_SUPERHERORES.BAK';

--B) RESTAURAR BD CON EL RESPALDO 1 DE SUPERHERORES
RESTORE DATABASE SUPERHERORES
FROM DISK = 'C:\ABD2022\U4\RespaldoFull_SUPERHERORES.BAK'
WITH
REPLACE,
RECOVERY,
STATS = 10;

--C) REVISA LA BD HACIENDO SELECT EN LAS DIFERENTES TABLAS Y VERIFICANDO LA ESTRUCTURA DE LA BD, PON EN COMENTARIOS COMO QUEDO LA BASE DE DATOS
--La BD quedo como si no huebieramos modificado nada, es decir que se perdieron las modificiones que hicimos.
--Por ejemplo ahora no tenemos la tabla universo y no esta relacionada con heroes.
SELECT * FROM HEROES;
SELECT * FROM HEROESvsVILLANOS;
SELECT * FROM HISTORIAL_HEROES;
SELECT * FROM LUGARES_DEFENSA;
SELECT * FROM PODERES;
SELECT * FROM PODERES_HEROES;
SELECT * FROM PODERES_VILLANOS;
SELECT * FROM TRAJES;
SELECT * FROM VILLANOS;

--Restaurar la BD de
RESTORE DATABASE SUPERHERORES
FROM DISK = 'C:\ABD2022\U4\SUPERHERORES_Full3.BAK'
WITH REPLACE, NORECOVERY;

RESTORE DATABASE SUPERHERORES
FROM DISK = 'C:\ABD2022\U4\SUPERHERORES_Dif3.BAK'
WITH REPLACE, RECOVERY;

--BORRAR LA BD
DROP DATABASE SUPERHERORES;

--RESTAURAR PARA VOLVER A TENER lA BD PERO CON EL BACKUP FULL 2
RESTORE DATABASE SUPERHERORES
FROM DISK = 'C:\ABD2022\U4\SUPERHERORES_Full2.BAK'
WITH REPLACE, NORECOVERY;

RESTORE DATABASE SUPERHERORES
FROM DISK = 'C:\ABD2022\U4\SUPERHERORES_Dif2.BAK'
WITH REPLACE, RECOVERY;

--VOLVER A RESTAURAR TODO PERO CON EL ULTIMO BACKUP COMPLETO QUE HICIMOS
RESTORE DATABASE SUPERHERORES
FROM DISK = 'C:\ABD2022\U4\SUPERHERORES_Full3.BAK'
WITH REPLACE, NORECOVERY;

RESTORE DATABASE SUPERHERORES
FROM DISK = 'C:\ABD2022\U4\SUPERHERORES_Dif3.BAK'
WITH REPLACE, RECOVERY;

--HACER RESPALDO COMPLETO
BACKUP DATABASE SUPERHERORES
TO DISK = 'C:\ABD2022\U4\SUPERHERORES_Full4.BAK'
WITH
NAME = 'SUPERHERORES_Full4',
DESCRIPTION = 'RESP. COMPLETO 4',
STATS = 10,
COMPRESSION;