--PRACTICA 1
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 26/04/22
--DESCRIPCION: Aprender a crear backups

--CREAR LA BD
CREATE DATABASE BDRespaldos
ON PRIMARY
(
	NAME = 'BDRespaldos.MDF',
	FILENAME = 'C:\ABD2022\U4\BDRespaldos.MDF'
)
LOG ON
(
NAME = 'BDRespaldos.LDF',
FILENAME ='C:\ABD2022\U4\BDRespaldos.LDF'
);

--PONER EN USO LA BD
USE BDRespaldos;

--CREAR TABLA LLAMADA DATOS
CREATE TABLE DATOS(
id INT IDENTITY(1,1) PRIMARY KEY,
valor VARCHAR(50)
);

--INSERTAR 50 REGISTROS EN LA TABLA DE DATOS
INSERT INTO DATOS VALUES ('Soy un dato')
GO 50

--CREAR BACKUP COMPLETO DE LA BD
BACKUP DATABASE BDRespaldos
TO DISK = 'C:\ABD2022\U4\Respaldo1_BDRespaldos.BAK'
WITH
NAME = 'RESPALDO de BDRespaldos',
DESCRIPTION = 'PRIMER RESPALDO SOLO TIENE UNA TABLA CON 50 REGISTROS';

--INSERTAR 30 REGISTROS EN LA TABLA DE DATOS
INSERT INTO DATOS VALUES ('OTROS DATOS')
GO 30

--BORRAR REGISTROS EN LA TABLA DE DATOS
DELETE FROM DATOS WHERE id BETWEEN 25 AND 40;

--CREAR BACKUP DIFERENCIAL DE LA BD
BACKUP DATABASE BDRespaldos
TO DISK = 'C:\ABD2022\U4\DIFERENCIAL1_BDRespaldos.BAK'
WITH DIFFERENTIAL,
NAME = 'DIFERENCIAL1_BDRespaldos',
DESCRIPTION = 'BD DESPUES DE INSERTAR Y BORRAR',
STATS = 3;

--CREAR TABLA LLAMADA MISDATOS
CREATE TABLE MISTADOS(
MIID INT IDENTITY(1,1) PRIMARY KEY,
MIVALOR VARCHAR(50)
);

--CREAR SEGUNDO RESPALDO DIFERENCIAL DE LA BD
BACKUP DATABASE BDRespaldos
TO DISK = 'C:\ABD2022\U4\DIF2_BDRespaldos.BAK'
WITH DIFFERENTIAL,
NAME = 'DIFERENCIAL2_BDRespaldos',
DESCRIPTION = 'BD DESPUES DE AGREGAR TABLA',
EXPIREDATE = '2022-08-21',
STATS = 10;