--PRACTICA 7
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 29/04/22
--DESCRIPCION: Aprender la creacion de backups divididos

USE GUARDERIA;

--CONTAR CUANTOS REGISTROS HAY EN CADA TABLA
SELECT COUNT(*) FROM ALUMNO;
SELECT COUNT(*) FROM ENCARGADO;
SELECT COUNT(*) FROM INCIDENCIAS;
SELECT COUNT(*) FROM REGISTRO_ENT_SAL;
SELECT COUNT(*) FROM SALA;

--REALIZAR UN RESPALDO COMPLETO DE DIVIDIDA EN TRES ARCHIVOS EN DIFERENTES CARPETAS DE LA BD GUARDERIA
BACKUP DATABASE GUARDERIA
TO
DISK = 'C:\ABD2022\U4\GuarderiaRespaldo1\Res1Guarderia.BAK',
DISK = 'C:\ABD2022\U4\GuarderiaRespaldo2\Res2Guarderia.BAK',
DISK = 'C:\ABD2022\U4\GuarderiaRespaldo3\Res3Guarderia.BAK'
WITH
STATS = 10;


--************************************************************************************************
SELECT TOP(1) * FROM ALUMNO ORDER BY ALU_ID DESC;
SELECT TOP(1) * FROM ENCARGADO ORDER BY ENC_ID DESC;--
SELECT TOP(1) * FROM INCIDENCIAS ORDER BY REP_ID DESC;--
SELECT TOP(1) * FROM REGISTRO_ENT_SAL ORDER BY REG_ID DESC;--

----03/05/2022----
DECLARE @ALU_ID INT = 964;
BEGIN TRAN
WHILE @ALU_ID <= 974
BEGIN 
INSERT INTO ALUMNO VALUES
(@ALU_ID, 'Evelyn Losada', 4,'2022-05-03', 'TUTOR', 'P1A')
SET @ALU_ID = @ALU_ID + 1;
END
COMMIT TRAN
GO

DECLARE @ENC_FECHAING DATETIME = '2022-05-01';
BEGIN TRAN
WHILE @ENC_FECHAING <= '2022-05-11'
BEGIN 
INSERT INTO ENCARGADO VALUES
('TRAB. SOCIAL', 'Toni Torregrosa', 'Calle Siempre Viva', '311-201-00-00', @ENC_FECHAING)
SET @ENC_FECHAING = DATEADD(DAY, 1, @ENC_FECHAING);
END
COMMIT TRAN
GO

DECLARE @REP_FECHA DATETIME = '2022-05-01 20:00:14.510';
DECLARE @ALU_ID INT = 964;
DECLARE @ENC_ID INT = 100;
BEGIN TRAN
WHILE @ALU_ID <= 974
BEGIN 
INSERT INTO INCIDENCIAS VALUES
('8:14', @REP_FECHA, @ENC_ID, @ALU_ID, 'BIEN')
SET @REP_FECHA = DATEADD(DAY, 1, @REP_FECHA);
SET @ALU_ID = @ALU_ID + 1;
SET @ENC_ID = @ENC_ID + 100;
END
COMMIT TRAN
GO

DECLARE @REG_FECHA DATETIME = '2022-05-01 20:00:00.510';
DECLARE @ALU_ID INT = 964;
BEGIN TRAN
WHILE @ALU_ID <= 974
BEGIN 
INSERT INTO REGISTRO_ENT_SAL VALUES
('8:00', @REG_FECHA, 'E', @ALU_ID)
SET @REG_FECHA = DATEADD(DAY, 1, @REG_FECHA);
SET @ALU_ID = @ALU_ID + 1;
END
COMMIT TRAN
GO

----06/05/2022----
DECLARE @ALU_ID INT = 975;
BEGIN TRAN
WHILE @ALU_ID < 985
BEGIN 
INSERT INTO ALUMNO VALUES
(@ALU_ID, 'Alejandro Diaz', 4,'2022-05-03', 'TUTOR', 'P1A')
SET @ALU_ID = @ALU_ID + 1;
END
COMMIT TRAN
GO

DECLARE @REP_FECHA DATETIME = '2022-05-06 12:00:14.510';
DECLARE @ALU_ID INT = 975;
DECLARE @ENC_ID INT = 100;
BEGIN TRAN
WHILE @ALU_ID < 984
BEGIN 
INSERT INTO INCIDENCIAS VALUES
('12:00', @REP_FECHA, @ENC_ID, @ALU_ID, 'BIEN')
SET @REP_FECHA = DATEADD(DAY, 1, @REP_FECHA);
SET @ALU_ID = @ALU_ID + 1;
SET @ENC_ID = @ENC_ID + 100;
END
COMMIT TRAN
GO

DECLARE @REG_FECHA DATETIME = '2022-05-01 07:00:00.510';
DECLARE @ALU_ID INT = 975;
BEGIN TRAN
WHILE @ALU_ID < 984
BEGIN 
INSERT INTO REGISTRO_ENT_SAL VALUES
('7:00', @REG_FECHA, 'E', @ALU_ID)
SET @REG_FECHA = DATEADD(DAY, 1, @REG_FECHA);
SET @ALU_ID = @ALU_ID + 1;
END
COMMIT TRAN
GO

--************************************************************************************************