--PRACTICA 15
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 07/05/22
--DESCRIPCION: Practicar la exportacion e importacion con bulk insert, bcp y el wizard

--CREAR LA BD
CREATE DATABASE PRESTAMOS
ON PRIMARY
(
	NAME = 'PRESTAMOS.MDF',
	FILENAME = 'C:\ABD2022\U4\PRESTAMOS.MDF'
)
LOG ON
(
	NAME = 'PRESTAMOS.LDF',
	FILENAME = 'C:\ABD2022\U4\PRESTAMOS.LDF'
);

--PONER EN USO LA BD
USE PRESTAMOS;

--CREATE TABLA DE DEUDOR
CREATE TABLE DEUDOR(
	DEUID INT PRIMARY KEY IDENTITY(1,1),
	DEUNOMBRE VARCHAR(100),
	DEUDOMICILIO VARCHAR(100),
	DEUTELEFONO VARCHAR(15),
	DEULIMCRE MONEY,
);

--CREAR TABLA DE PRESTAMOS
CREATE TABLE PRESTAMOS(
	PREID INT PRIMARY KEY IDENTITY(1,1),
	DEUID INT REFERENCES DEUDOR(DEUID),
	PREFECHAIN DATETIME,
	PREIMPORTE MONEY,
	PRENOABONO SMALLINT,
	PREABONOX MONEY,
	PRESALDO MONEY,
	PREINTERES SMALLINT,
	PREFECHALIQUIDADOS DATETIME,
	PRESEXO CHAR(1)
);

--CREATE TABLA DE ABONO
CREATE TABLE ABONO(
	PREID INT REFERENCES PRESTAMOS(PREID),
	ABOID INT,
	ABOFECHA DATETIME,
	ABOIMPORTE MONEY,
	ABOFORMATO CHAR(1)
);

--B) MIGRAR LOS DEUDORES POR MEDIO DE UN COMANDO BULK INSERT DEL ARCHIVO (DEUDORES.TXT)
BULK INSERT DEUDOR
FROM 'C:\ABD2022\U4\DEUDORES.TXT'
WITH (FIELDTERMINATOR = ',');

--COMPROBAMOS
SELECT * FROM DEUDOR;

--C) REALIZA UN RESPALDO COMPLETO DE LA BD CON AL MENOS 3 PARAMETROS.
BACKUP DATABASE PRESTAMOS
TO DISK = 'C:\ABD2022\U4\PRESTAMOS_COMPLETO1.BAK'
WITH
NAME = 'PRESTAMOS_COMPLETO1',
DESCRIPTION = 'Se migraron los deudores de DEUDORES.TXT con BULK INSERT',
STATS = 10;

--D) MIGRA LOS PRESTAMOS CON EL COMANDO BCP DEL ARCHIVO (PRESTAMOS.TXT)
--Comando BCP: BCP "PRESTAMOS.DBO.PRESTAMOS" IN "C:\ABD2022\U4\Prestamo.TXT" -c -T -t ","

--COMPROBAMOS
SELECT * FROM PRESTAMOS;

--E) REALIZA UN RESPALDO DIFERENCIAL CON AL MENOS 3 PARAMETROS.
BACKUP DATABASE PRESTAMOS
TO DISK = 'C:\ABD2022\U4\PRESTAMOS_DIFERENCIAL1.BAK'
WITH DIFFERENTIAL,
NAME = 'PRESTAMOS_DIFERENCIAL1',
DESCRIPTION = 'Se migraron los prestamos de PRESTAMOS.TXT con BCP',
STATS = 10;


--F) MIGRA LOS ABONOS POR MEDIO DE LA HERRAMIENTA GRAFICA DEL ARCHIVO (ABONO.XLS)

--BORRAR LOS REGISTROS CON NULL
DELETE FROM ABONO WHERE ABOID IS NULL;

--COMPROBAMOS
SELECT * FROM ABONO;

--G) REALIZA UN RESPALDO DIFERENCIAL
BACKUP DATABASE PRESTAMOS
TO DISK = 'C:\ABD2022\U4\PRESTAMOS_DIFERENCIAL2.BAK'
WITH DIFFERENTIAL,
NAME = 'PRESTAMOS_DIFERENCIAL2',
DESCRIPTION = 'Se migraron los abonos de ABONO.XLS con el wizard',
STATS = 10;

--H) INSERTA UN ABONO DE TODOS LOS PRESTAMOS QUE NO ESTAN LIQUIDADOS DE
--100 PESOS CON LA FECHA DE HOY POR QUE ES UN REGALO POR EL DIA DE LA
--MUJER QUE LE VA DAR EL DUEÑO DE LA EMPRESA (PRESTAMO LIQUIDADO= SALDO 0)

DECLARE @ABOID INT, @PREID INT;
SET @ABOID = 53;
SET @PREID = 1;
BEGIN TRAN
WHILE @PREID IS NOT NULL
BEGIN 
INSERT INTO ABONO (PREID, ABOFECHA, ABOIMPORTE) SELECT PREID, GETDATE(), 100 FROM PRESTAMOS WHERE PREFECHALIQUIDADOS IS NULL;
SET @ABOID = @ABOID + 1;
SELECT @PREID = PREID FROM PRESTAMOS WHERE PREFECHALIQUIDADOS IS NULL;
IF @PREID IS NULL
BREAK
END
COMMIT TRAN;

--I) REALIZA UN RESPALDO DIFERRENCIAL
BACKUP DATABASE PRESTAMOS
TO DISK = 'C:\ABD2022\U4\PRESTAMOS_DIFERENCIAL3.BAK'
WITH DIFFERENTIAL,
NAME = 'PRESTAMOS_DIFERENCIAL3',
DESCRIPTION = 'Se inserto en abonos',
STATS = 10;

--J) OOOH OOOOH!!! HUBO UN ERROR GARRAFATAL DEBERIAS DE HABER HECHO
--LOS ABONOS A LOS PRESTAMOS QUE PERTENCEN A MUJERES. ARREGLA LAS COSAS
--Y SOLO DALE EL BENEFICIO A QUIEN LE CORRESPONDE.
RESTORE DATABASE PRESTAMOS
FROM DISK = 'C:\ABD2022\U4\PRESTAMOS_COMPLETO1.BAK'
WITH REPLACE, NORECOVERY;

RESTORE DATABASE PRESTAMOS
FROM DISK = 'C:\ABD2022\U4\PRESTAMOS_DIFERENCIAL2.BAK'
WITH REPLACE, RECOVERY;

UPDATE ABONO
SET ABOIMPORTE = 100
WHERE PREID = (SELECT PREID FROM PRESTAMOS WHERE PRESEXO = 'F');