--PRACTICA 14
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 06/05/22
--DESCRIPCION: Practicar la restauracion con cambio en la ubicacion del MDF y LDF.

--RESTAURA EL PRIMER RESPALDO COMPLETO DE NORTHWIND, EN OTRA 
--UBICACIÓN Y CON OTRO NOMBRE EL NOMBRE DEBE SER : TESTER_NORTWIND, 
--LA UBICACIÓN NUEVA TU LA ELIGES
RESTORE FILELISTONLY
FROM DISK = 'C:\ABD2022\U4\RespaldoFull_Northwind.BAK';
--Northwind_data
--Northwind_log

RESTORE DATABASE Northwind
FROM DISK = 'C:\ABD2022\U4\RespaldoFull_Northwind.BAK'
WITH
MOVE 'Northwind_data'
TO 'C:\ABD2022\U4\Practica14\TESTER_NORTWIND.MDF',
MOVE 'Northwind_log'
TO 'C:\ABD2022\U4\Practica14\TESTER_NORTWIND.LDF';