--PRACTICA 10
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 03/05/22
--DESCRIPCION: Practicar la restauracion de backups

--PONER EN USO LA BD
USE Northwind;

--A. RESTAURA EL HEADER DEL PRIMER BACKUP COMPLETO NORTWIND QUE REALIZASTE.
RESTORE HEADERONLY
FROM DISK= 'C:\ABD2022\U4\RespaldoFull_Northwind.BAK';
--Completo1 de Northwind

--B. RESTAURA EL RESPALDO COMPLETO.
RESTORE DATABASE Northwind
FROM DISK = 'C:\ABD2022\U4\RespaldoFull_Northwind.BAK'
WITH REPLACE, RECOVERY;

--C. REVISA LA BD HACIENDO SELECT EN LAS DIFERENTES TABLAS Y VERIFICANDO LA ESTRUCTURA DE LA BD,
--   PON EN COMENTARIOS COMO QUEDO LA BASE DE DATOS
SELECT * FROM Categories;
SELECT * FROM CustomerCustomerDemo;
SELECT * FROM CustomerDemographics;
SELECT * FROM Customers;
SELECT * FROM Employees;
SELECT * FROM EmployeeTerritories
SELECT * FROM [Order Details];
SELECT * FROM Orders;
SELECT * FROM Products;
SELECT * FROM Region;
SELECT * FROM Shippers;
SELECT * FROM Suppliers;
SELECT * FROM Territories;
--LA BD QUEDO COMO SI NUNCA HUBIERAMOS HECHO NINGUN CAMBIO. YA ES LA "ORIGINAL".

/*
  D) SUPONGA QUE HUBO UN ERROR AL PROCESAR LA INFORMACIÓN NO DEBIMOS INSERTAR
  LOS 20 PRODUCTOS NI ACTUALIZAR LAS EDADES DE LOS EMPLEADOS EN EL PUNTO 9 DE LA
  PRACTICA 2. REALIZA LA RESTAURACIÓN DE (L)O(S) CORRESPONDIENTES PARA PONER
  RECUPERAR LA BD AL MOMENTO ANTES DE HABER COMENTIDO EL ERROR.
  Y VERIFIQUE QUE INFORMACION PERDIMOS.
*/

RESTORE DATABASE Northwind
FROM DISK = 'C:\ABD2022\U4\RespaldoFull_Northwind.BAK'
WITH REPLACE, NORECOVERY;

RESTORE DATABASE Northwind
FROM DISK = 'C:\ABD2022\U4\RespaldoDif2_Northwind.BAK'
WITH REPLACE, RECOVERY;

--PERDIMOS LO QUE HICIMOS EN EL PUNTO  11 Y 12.
--CREA UNA TABLA CON LOS EMPLEADOS QUE NO HAN VENDIDO ORDENES y BORRA LOS EMPLEADOS QUE NO HAN VENDIDO ORDENES
SELECT E.EmployeeID, E.FirstName, E.LastName, E.Title, E.BirthDate, E.ReportsTo
INTO EmpleadosNoOrdenes
FROM Employees E
INNER JOIN VISTA_Empleados_Ordenes VEO ON (E.EmployeeID = VEO.EmployeeID)
WHERE VEO.[NO. ORDENES] = 0;

DELETE FROM Employees
WHERE EmployeeID IN (SELECT EmployeeID FROM VISTA_Empleados_Ordenes VEO WHERE VEO.[NO. ORDENES] = 0);

/*
  E) HUBO UN ERROR DE CRITERIO, TODO LO QUE SE HABIA REALIZADO EN LA BD DE DATOS
  ERA CORRECTO ASI QUE ES NECEARIO RECUPERARLA HASTA LA ULTIMA MODIFICACION QUE
  SE REALIZO.
*/
RESTORE DATABASE Northwind
FROM DISK = 'C:\ABD2022\U4\RespaldoFull2_Northwind.BAK'
WITH REPLACE, NORECOVERY;

RESTORE DATABASE Northwind
FROM DISK = 'C:\ABD2022\U4\RespaldoDif5_Northwind.BAK'
WITH REPLACE, RECOVERY;