--PRACTICA 4
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 28/04/22
--DESCRIPCION: Practicar la creacion de backups

--PONER EN USO LA BD
USE SUPERHERORES;

--CONTAR CUANTOS REGISTROS HAY EN CADA TABLA
SELECT COUNT(*) FROM HEROES;
SELECT COUNT(*) FROM HEROESvsVILLANOS;
SELECT COUNT(*) FROM HISTORIAL_HEROES;
SELECT COUNT(*) FROM LUGARES_DEFENSA;
SELECT COUNT(*) FROM PODERES;
SELECT COUNT(*) FROM PODERES_HEROES;
SELECT COUNT(*) FROM PODERES_VILLANOS;
SELECT COUNT(*) FROM TRAJES;
SELECT COUNT(*) FROM VILLANOS;

--2. CREAR UN RESPALDO COMPLETO CON FORMAT, NOMBRE, DESCRIPCION, STATS Y RETAINDAYS, COMPRESION
BACKUP DATABASE SUPERHERORES
TO DISK = 'C:\ABD2022\U4\RespaldoFull_SUPERHERORES.BAK'
WITH NAME = 'RespaldoFull_SUPERHERORES',
DESCRIPTION = 'Primer respaldo completo',
RETAINDAYS = 10,
STATS = 5,
COMPRESSION,
FORMAT;

--3. INSERTA AL 10 SUPERHEROES Y SUS ENEMIGOS RESPECTIVOS EN LA TABLA DE VILLANOS AL MENOS 3 PARA CADA UNO
INSERT INTO HEROES VALUES
('PETER PARKER', 'SPIDERMAN', 20, 1, 100, '', 1),
('TONY STARK', 'IRON', 40, 1, 50, '', 2),
('NATACHA ROMANOV', 'VIUDA NEGRA', 35, 1, 100, '', 5),
('ROBERTO GOMEZ', 'CHAPULIN COLORADO', 60, 1, 100, '', 7),
('THOR ODINSON', 'THOR', 50, 1, 50, '', 8),
('BARRY ALLEN', 'FLASH', 25, 1, 150, '', 10),
('BRUCE BANNER', 'HULK', 40, 1, 100, '', 9),
('STEVE ROGERS', 'CAPITAN AMERICA', 126, 1, 100, '', 4),
('MATH MURDO', 'DAREDEVIL', 30, 1, 200, '', 3),
('AANG', 'AVATAR', 112, 1, 50, '', 6);

INSERT INTO VILLANOS VALUES
('MISTERIO', 'MISTERIO', 2),
('NORAM OSBORN', 'DUENDE VERDE', 3),
('EDY BROCK', 'VENOM', 4),
('THANOS', 'THANOS', 5),
('MANDARIN', 'MANDARIN', 7),
('WASON', 'WASON', 10),
('KANG', 'KANG', 8),
('PINGUINO', 'PINGUINO', 3),
('RONAN', 'RONAN', 9),
('FLASH', 'FLASH', 3),
('RATERO', 'RATERO', 5),
('CRANEO ROJO', 'CRANEO ROJO', 8),
('ABOMINACION', 'ABOMINACION', 9),
('RED HULK', 'RED HULK', 6);

--4. INSERTA 10 LUGARES DE DEFENSA
INSERT INTO LUGARES_DEFENSA VALUES
('LUGAR DE DEFENSA 1'),
('LUGAR DE DEFENSA 2'),
('LUGAR DE DEFENSA 3'),
('LUGAR DE DEFENSA 4'),
('LUGAR DE DEFENSA 5'),
('LUGAR DE DEFENSA 6'),
('LUGAR DE DEFENSA 7'),
('LUGAR DE DEFENSA 8'),
('LUGAR DE DEFENSA 9'),
('LUGAR DE DEFENSA 10');

--5. CREA UN RESPALDO DIFERENCIAL CON NOMBRE, DESCRIPCION STATS, COMPRESION
BACKUP DATABASE SUPERHERORES
TO DISK = 'C:\ABD2022\U4\SUPERHERORES_Dif1.BAK'
WITH DIFFERENTIAL,
NAME = 'SUPERHERORES_Dif1',
DESCRIPTION = 'Se inserto en tabla defensa, heroes y villanos',
STATS = 10,
COMPRESSION;

--6. AGREGA UNA TABLA LLAMADA UNIVERSOS CON DOS CAMPOS UNIVERSO VARCHAR DE 10 COMO PK Y UN CAMPO DE DESCRIPCION
CREATE TABLE UNIVERSOS
(
Universo VARCHAR(10) PRIMARY KEY,
Descripcion VARCHAR(100)
);

--7. INSERTA LOS SIGUIENTES UNIVERSO Marvel y DC Comics
INSERT INTO UNIVERSOS VALUES
('Marvel', 'MARVEL'),
('DC Comics', 'DC COMICS');

--8. CREA UN RESPALDO COMPLETO CON TRES PARAMEROS
BACKUP DATABASE SUPERHERORES
TO DISK = 'C:\ABD2022\U4\SUPERHERORES_Full2.BAK'
WITH
NAME = 'SUPERHERORES_Full2',
DESCRIPTION = 'Se creo tabla univeros y se inserto dos campos',
STATS = 10;

--9. RELACIONALA LA TABLA DE UNIVERSOS CON SUPERHEROES
ALTER TABLE HEROES
ADD HER_UNIVERSO VARCHAR(10);

ALTER TABLE HEROES 
ADD CONSTRAINT FK_HEROES_UNIVERSO
FOREIGN KEY (HER_UNIVERSO) REFERENCES UNIVERSOS(UNIVERSO);

--10. ACTUALIZA EL UNIVERSO A CADA SUPERHEROE QUE TENGAS REGISTRADOS
UPDATE HEROES
SET HER_UNIVERSO = 'Marvel'
WHERE HER_ID BETWEEN 2 AND 3;

UPDATE HEROES
SET HER_UNIVERSO = 'DC Comics'
WHERE HER_ID BETWEEN 1002 AND 1006;

UPDATE HEROES
SET HER_UNIVERSO = 'Marvel'
WHERE HER_ID >= 1006;

--11. CREA UN RESPALDO DIFERENCIAL
BACKUP DATABASE SUPERHERORES
TO DISK = 'C:\ABD2022\U4\SUPERHERORES_Dif2.BAK'
WITH DIFFERENTIAL,
NAME = 'SUPERHERORES_Dif2',
DESCRIPTION = 'Se agrego llave foranea de univeros en heroes y se modifico el univers del heroe',
STATS = 10;

--12. INSERTA LOS PODERES AL MENOS UNO A CADA SUPERHEROE
INSERT INTO PODERES_HEROES VALUES
(3, 10),
(2, 20),
(1002, 30),
(1003, 40),
(1004, 50),
(1005, 60),
(1006, 70),
(1007, 80),
(1008, 90),
(1009, 100),
(1010, 110),
(1002, 90),
(1002, 110),
(1005, 70),
(1009, 20),
(1009, 30),
(1009, 40);

--13. CREA UN RESPALDO COMPLETO
BACKUP DATABASE SUPERHERORES
TO DISK = 'C:\ABD2022\U4\SUPERHERORES_Full3.BAK'
WITH
NAME = 'SUPERHERORES_Full3',
DESCRIPTION = 'Se agrego poderes a heroes',
STATS = 10;

--14. BORRA LOS TRAJES QUE NO ESTEN RELACIONADO CON NINGUN SUPERHEROE
DELETE FROM TRAJES
WHERE TRA_ID NOT IN (SELECT H.TRA_ID FROM HEROES H);

--15. CREA UN RESPALDO DIFERENCIAL
ALTER DATABASE SUPERHERORES
SET RECOVERY FULL;

BACKUP DATABASE SUPERHERORES
TO DISK = 'C:\ABD2022\U4\SUPERHERORES_Dif3.BAK'
WITH DIFFERENTIAL,
NAME = 'SUPERHERORES_Dif3',
DESCRIPTION = 'Se borro trajes que no estan relacionados con heroes',
STATS = 10;

--16. CREA UN RESPALDO DE LOG
BACKUP LOG SUPERHERORES
TO DISK = 'C:\ABD2022\U4\SUPERHERORES_ResLog1.TRN'
WITH
NAME = 'SUPERHERORES_ResLog1',
DESCRIPTION = 'Primer backup del log',
STATS = 10;