--PRACTICA 12
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 31/03/22
--DESCRIPCION: PRACTICAR LA CREACION DE PARTICIONES

--PONER EN USO LA BD
USE OFICIALIADEPARTES;

--2. INSERTE LOS SIGUIENTES DATOS A LA TABLA DE DOCUMENTOS
--(OFICIOS, MEMORANDUM, TARJETA INFORMATIVA, RECONOCIMIENTO)

INSERT INTO TIPOS_DOCTOS VALUES 
('OFICIOS'),
('MEMORANDUM'),
('TARJETA INFORM'),
('RECONOCIMIENTO');

--3. INSERTA AL MENOS 10 DESTINATARIOS - EMISORES
INSERT INTO DESTINATARIO_EMISOR VALUES
('CESAR INZUNSA', 'DIRECTOR', 'PALACIO', 'TEPIC'),
('JUAN GOMEZ', 'SUPERVISOR', 'CONAGUA', 'TEPIC'),
('FERNANDO', 'SUPERVISOR GENERAL', 'PALACIO', 'TEPIC'),
('MARIA', 'GERENTE', 'PALACIO', 'TEPIC'),
('JUAN GUTIERREZ', 'DIRECTOR', 'PALACIO', 'TEPIC'),
('RICARDO JAVIER', 'DIRECTOR', 'PALACIO', 'TEPIC'),
('VERONICA JUDITH', 'DIRECTOR', 'PALACIO', 'TEPIC'),
('OMAR ABISAI', 'DIRECTOR', 'PALACIO', 'TEPIC'),
('ALEXA DANIELA', 'DIRECTOR', 'PALACIO', 'TEPIC'),
('KEVIN JAVIER', 'DIRECTOR', 'PALACIO', 'TEPIC');

--4. INSERTA USANDO GO# DOCUMENTOS RECIBIDOS EN LA TABLA DE RECEPCION,
--    DEBES INSERTAR DE LOS DIFERENTES TIPOS DE DOCUMENTOS ASÍ QUE USA EL GO CON DIFERENTES CANTIDADES:
--    SON 50, 000.

INSERT INTO RECEPCION VALUES
('1234567890', '2018-01-01', 4, 10, 20, 'CAMBIOS EN LA FECHA DE REUNION')
GO 10000

INSERT INTO RECEPCION VALUES
('1234567891', '2019-02-02', 5, 20, 30, 'CAMBIO DE FECHA EN EVENTO')
GO 10000

INSERT INTO RECEPCION VALUES
('1234567892', '2020-03-03', 6, 30, 40, 'EVENTO DEPORTIVO')
GO 10000

INSERT INTO RECEPCION VALUES
('1234567893', '2021-04-04', 7, 40, 50, 'CAMBIOS ESTRUCTURALES IMPORTANTES')
GO 10000

INSERT INTO RECEPCION VALUES
('1234567894', '2022-05-05', 4, 50, 60, 'CAMBIOS IMPORTANTES EN PROYECTO')
GO 10000

--5. DEBE PARTICIONAR LA TABLA DE RECEPCION, USTED DECIDA COMO SE DEBE PARTICIONAR CON QUE CAMPO Y CON QUE ENFOQUE.

--EL PARTICIONAMIENTO LO HAREMOS DE FORMA HORIZONTAL,
--EL ENFOQUE SE REFIERE A QUE SI QUEREMOS HACER UNA TABLA EXRA PARA REALIZAR EL PARTICIONADO O SI QUEREMOS HACERLO DE FORMA DIRECTA

--PASO 1: CREAR LOS FILEGROUP
ALTER DATABASE OFICIALIADEPARTES
ADD FILEGROUP Recep2018;

ALTER DATABASE OFICIALIADEPARTES
ADD FILEGROUP Recep2019;

ALTER DATABASE OFICIALIADEPARTES
ADD FILEGROUP Recep2020;

ALTER DATABASE OFICIALIADEPARTES
ADD FILEGROUP Recep2021;

ALTER DATABASE OFICIALIADEPARTES
ADD FILEGROUP Recep2022;

--PASO 2: CREAR LOS ARCHIVOS NDF
ALTER DATABASE OFICIALIADEPARTES
ADD FILE
(
	NAME = 'Recep2018.NDF',
	FILENAME = 'C:\ABD2022\U3\DISCO1\Recep2018.NDF'
)
TO FILEGROUP Recep2018;

ALTER DATABASE OFICIALIADEPARTES
ADD FILE
(
	NAME = 'Recep2019.NDF',
	FILENAME = 'C:\ABD2022\U3\DISCO2\Recep2019.NDF'
)
TO FILEGROUP Recep2019;

ALTER DATABASE OFICIALIADEPARTES
ADD FILE
(
	NAME = 'Recep2020.NDF',
	FILENAME = 'C:\ABD2022\U3\DISCO3\Recep2020.NDF'
)
TO FILEGROUP Recep2020;

ALTER DATABASE OFICIALIADEPARTES
ADD FILE
(
	NAME = 'Recep2021.NDF',
	FILENAME = 'C:\ABD2022\U3\DISCO4\Recep2021.NDF'
)
TO FILEGROUP Recep2021;

ALTER DATABASE OFICIALIADEPARTES
ADD FILE
(
	NAME = 'Recep2022.NDF',
	FILENAME = 'C:\ABD2022\U3\DISCO5\Recep2022.NDF'
)
TO FILEGROUP Recep2022;

--PASO 3: CREAR LA FUNCION DE PARTICION
CREATE PARTITION FUNCTION F_ParticionPorFecha(DATE)
AS RANGE RIGHT FOR VALUES ('2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01');

--PASO 4: CREAR EL ESQUEMA DE PARTICION
CREATE PARTITION SCHEME EsquemaByFecha
As PARTITION F_ParticionPorFecha
TO (
Recep2018, 
Recep2019, 
Recep2020, 
Recep2021, 
Recep2022
);

--PASO 5: CREAR TABLA DE Recepcion 2
CREATE TABLE Recepcion_Particionada(
	REC_ID INT PRIMARY KEY NONCLUSTERED,
	REC_NODOCTO VARCHAR(10),
	REC_FECHA DATE,
	TIP_ID TINYINT REFERENCES TIPOS_DOCTOS(TIP_ID),
	REC_EMISOR INT REFERENCES DESTINATARIO_EMISOR(RE_ID),
	REC_DESTINATARIO INT REFERENCES DESTINATARIO_EMISOR(RE_ID),
	REC_ASUNTO VARCHAR(MAX)
);

--CREAR INDEX CLUSTERED
CREATE CLUSTERED INDEX IDX_Recepcion_Particionada
ON Recepcion_Particionada (REC_FECHA)
ON EsquemaByFecha (REC_FECHA);

--VACIAR REGISTROS EN LA TABLA NUEVA Y VERIFICAR
INSERT INTO Recepcion_Particionada SELECT * FROM RECEPCION;
SELECT COUNT(*) FROM Recepcion_Particionada;

--BORRAR LLAVES FORANEAS
ALTER TABLE SEGUIMIENTO
DROP CONSTRAINT FK_SEG_RECEPCION;

--BORRAR TABLA DE RECEPCION
DROP TABLE RECEPCION;

--CAMBIAR EL NOMBRE A LA TABLA NUEVA POR LA DE REPORTES
EXEC sp_rename 'Recepcion_Particionada', 'RECEPCION';

--CREAR LLAVE FORANEA EN REPORTES
ALTER TABLE SEGUIMIENTO
ADD CONSTRAINT FK_SEG_RECEPCION FOREIGN KEY(REC_ID)
REFERENCES RECEPCION(REC_ID);

--VERIFICAR SI SE CREARIB KIS FIILEGROUPS Y DATAFILES
SELECT name AS NombresFilegroups
FROM sys.filegroups
WHERE type = 'FG';

SELECT name AS [FIleName], physical_name AS [FilePath]
FROM sys.database_files
WHERE TYPE_DESC = 'ROWS';

--MOSTRAR CUANTOS REGISTROS TIENE CADA PARTICION
SELECT p.partition_number AS Num_Particion, f.name AS Nombre, p.rows AS Columnas
FROM sys.partitions p
JOIN sys.destination_data_spaces dds ON p.partition_number = dds.destination_id
JOIN sys.filegroups f ON dds.data_space_id = f.data_space_id
WHERE OBJECT_NAME(OBJECT_ID) = 'RECEPCION'
AND p.index_id = 1;

--MUESTRE LOS REGISTROS DE LA TABLA
SELECT * FROM RECEPCION;

--MUESTRE LOS REGISTROS DE CADA PARTICION
SELECT * FROM RECEPCION WHERE $partition.F_ParticionPorFecha(REC_FECHA) = 1;
SELECT * FROM RECEPCION WHERE $partition.F_ParticionPorFecha(REC_FECHA) = 2;
SELECT * FROM RECEPCION WHERE $partition.F_ParticionPorFecha(REC_FECHA) = 3;
SELECT * FROM RECEPCION WHERE $partition.F_ParticionPorFecha(REC_FECHA) = 4;
SELECT * FROM RECEPCION WHERE $partition.F_ParticionPorFecha(REC_FECHA) = 5;