--PRACTICA 6
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 17/03/22
--DESCRIPCION: Aprender a crear indices clusterados y no clustereados.


--CREACIÓN DE LA BD
CREATE DATABASE ABD2022
ON PRIMARY
(
	NAME = 'ABD2022.MDF',
	FILENAME = 'C:\ABD2022\U3\ABD2022.MDF'
)
LOG ON
(
	NAME = 'ABD2022.LDF',
	FILENAME ='C:\ABD2022\U3\ABD2022.LDF'
);

--PONER EN USO LA BD
USE ABD2022;

--CREAR TABLA ALUMNOS_ABD
CREATE TABLE ALUMNOS_ABD
(
	ALU_ID INT,
	ALU_NOMBRE VARCHAR(30),
	ALU_APEPAT VARCHAR(30),
	ALU_APEMAT VARCHAR(30),
	ALU_EDAD SMALLINT,
);

--A) CREA UN INDICE CLUSTEREADO CON EL ID.
CREATE CLUSTERED INDEX indice_clusteredAlumnosId ON ALUMNOS_ABD(ALU_ID);

--B) CREA UN INDICE NOCLUSTEREADO CON EL SEGUNDO CAMPO.
CREATE NONCLUSTERED INDEX indice_NoclusteredAlumnosNombre ON ALUMNOS_ABD(ALU_NOMBRE);

--C) CREA UN INDICE NOCLUSTEREADO CON LA COMBINACION DE LOS CAMPOS QUE FORMAN EL NOMBRE COMPLETO.
CREATE NONCLUSTERED INDEX indice_NoclusteredAlumnosNombreCompleto ON ALUMNOS_ABD(ALU_NOMBRE, ALU_APEPAT, ALU_APEMAT);


--D) INSERTAR REGISTROS
INSERT INTO ALUMNOS_ABD VALUES
(1, 'Cesar', 'Inzunsa', 'Diaz', 21),
(2, 'Mark', 'Oliva', 'Cardenas', 22),
(3, 'Bartolome', 'Bueno', 'Botella', 23),
(4, 'Dolores', 'Arias', 'Rebollo', 24),
(5, 'Salvadora', 'Caamaño', 'Diaz', 25),
(6, 'Ignacio', 'Sempere', 'Coll', 26),
(7, 'Carmela', 'Llopis', 'San Martin', 27),
(8, 'Hortensia', 'Carretero', 'Perez', 17),
(9, 'Elias', 'Acuña', 'Rebollo', 19),
(10, 'Rayan', 'Alvaro', 'Botella', 29);

--E) HAGA CONSULTAS CON WHERE Y ORDER BY. Y MUESTRE EL PLAN DE EJECUCION (ESTO TAMBIEN IRIA EN EL RESULTADO).
SELECT * FROM ALUMNOS_ABD WHERE ALU_ID = 1 AND ALU_APEPAT='Inzunsa';
SELECT * FROM ALUMNOS_ABD ORDER BY ALU_NOMBRE DESC;
