--PRACTICA 9
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 26/05/22
--DESCRIPCION: Practicar la creacion de bitacoras con triggers

--PONER EN USO LA BD
USE PRESTAMOS;


--CREACION DEL TRIGGER PARA DEUDOR
CREATE TRIGGER TR_MOVTOS_DEUDOR ON DEUDOR FOR INSERT, UPDATE, DELETE AS
BEGIN 
	SET NOCOUNT ON;
	
	DECLARE @ID INT, @IMPORTE MONEY, @OPERACION VARCHAR(15);
	DECLARE @CANTINSERT INT, @CANTDELETE INT;
	DECLARE @CURSOR1 CURSOR;

	IF NOT EXISTS (SELECT * FROM BITACORAS.sys.OBJECTS WHERE TYPE = 'U' AND NAME = 'BITACORA_PRESTAMOS')
	BEGIN
		CREATE TABLE BITACORAS.DBO.BITACORA_PRESTAMOS(
			TABLA VARCHAR(30),
			OPERACION VARCHAR(15),
			ID INT,
			IMPORTE MONEY,
			DESCIMPORTE VARCHAR(30)
		);
	END

	SET @CANTINSERT = (SELECT COUNT(*) FROM inserted);
	SET @CANTDELETE = (SELECT COUNT(*) FROM deleted);

	--UPDATE
	IF (@CANTINSERT > 0 AND @CANTDELETE > 0)
	BEGIN
		
		SET @OPERACION = 'UPDATE';
		SET @CURSOR1 = CURSOR FOR SELECT DEUID, DEULIMCRE FROM deleted;
	END
	ELSE
	BEGIN
		IF (@CANTINSERT >0 AND @CANTDELETE = 0)
		BEGIN
			SET @OPERACION = 'INSERT';
			SET @CURSOR1 = CURSOR FOR SELECT DEUID, DEULIMCRE FROM inserted;
		END
	ELSE
	BEGIN
		SET @OPERACION = 'DELETE';
		SET @CURSOR1 = CURSOR FOR SELECT DEUID, DEULIMCRE FROM deleted;
	END --FIN CUANDO FUE DELETE
	END

	--ABRIR CURSOR
	OPEN @CURSOR1;

	--POSICIONARNOS AL PRIMER REGISTRO
	FETCH FROM @CURSOR1 INTO @ID, @IMPORTE;

	WHILE (@@FETCH_STATUS = 0)
	BEGIN

		INSERT INTO BITACORAS.DBO.BITACORA_PRESTAMOS VALUES
		('DEUDOR', @OPERACION, @ID, @IMPORTE, 'DEULIMCRE');
		
		--MOVER AL SIGUIENTE REGISTRO
		FETCH NEXT FROM @CURSOR1 INTO @ID, @IMPORTE;
	END --FIN WHILE

	--CERRA EL CURSOR
	CLOSE @CURSOR1;
	--LIBERAR
	DEALLOCATE @CURSOR1;

END

--***********PROBAR TRIGGER*************--
DELETE FROM DEUDOR WHERE DEUID IN (62,63,64);

--VERIFICAR QUE SE REGISTRO EN LA BITACORA
SELECT * FROM BITACORAS.DBO.BITACORA_PRESTAMOS;


--CREACION DEL TRIGGER PARA ABONOS
CREATE TRIGGER TR_MOVTOS_ABONOS ON ABONO FOR INSERT, UPDATE, DELETE AS
BEGIN 
	SET NOCOUNT ON;
	
	DECLARE @ID INT, @IMPORTE MONEY, @OPERACION VARCHAR(15);
	DECLARE @CANTINSERT INT, @CANTDELETE INT;
	DECLARE @CURSOR1 CURSOR;

	IF NOT EXISTS (SELECT * FROM BITACORAS.sys.OBJECTS WHERE TYPE = 'U' AND NAME = 'BITACORA_PRESTAMOS')
	BEGIN
		CREATE TABLE BITACORAS.DBO.BITACORA_PRESTAMOS(
			TABLA VARCHAR(30),
			OPERACION VARCHAR(15),
			ID INT,
			IMPORTE MONEY,
			DESCIMPORTE VARCHAR(30)
		);
	END

	SET @CANTINSERT = (SELECT COUNT(*) FROM inserted);
	SET @CANTDELETE = (SELECT COUNT(*) FROM deleted);

	--UPDATE
	IF (@CANTINSERT > 0 AND @CANTDELETE > 0)
	BEGIN
		
		SET @OPERACION = 'UPDATE';
		SET @CURSOR1 = CURSOR FOR SELECT ABOID, ABOIMPORTE FROM deleted;
	END
	ELSE
	BEGIN
		IF (@CANTINSERT >0 AND @CANTDELETE = 0)
		BEGIN
			SET @OPERACION = 'INSERT';
			SET @CURSOR1 = CURSOR FOR SELECT ABOID, ABOIMPORTE FROM inserted;
		END
	ELSE
	BEGIN
		SET @OPERACION = 'DELETE';
		SET @CURSOR1 = CURSOR FOR SELECT ABOID, ABOIMPORTE FROM deleted;
	END --FIN CUANDO FUE DELETE
	END

	--ABRIR CURSOR
	OPEN @CURSOR1;

	--POSICIONARNOS AL PRIMER REGISTRO
	FETCH FROM @CURSOR1 INTO @ID, @IMPORTE;

	WHILE (@@FETCH_STATUS = 0)
	BEGIN

		INSERT INTO BITACORAS.DBO.BITACORA_PRESTAMOS VALUES
		('ABONO', @OPERACION, @ID, @IMPORTE, 'ABOIMPORTE');
		
		--MOVER AL SIGUIENTE REGISTRO
		FETCH NEXT FROM @CURSOR1 INTO @ID, @IMPORTE;
	END --FIN WHILE

	--CERRA EL CURSOR
	CLOSE @CURSOR1;
	--LIBERAR
	DEALLOCATE @CURSOR1;

END

--***********PROBAR TRIGGER*************--
UPDATE ABONO
SET ABOIMPORTE = 500
WHERE ABOID IN (1, 2, 3);

--VERIFICAR QUE SE REGISTRO EN LA BITACORA
SELECT * FROM BITACORAS.DBO.BITACORA_PRESTAMOS;

--CREACION DEL TRIGGER PARA PRESTAMOS
CREATE TRIGGER TR_MOVTOS_PRESTAMOS ON PRESTAMOS FOR INSERT, UPDATE, DELETE AS
BEGIN 
	SET NOCOUNT ON;
	
	DECLARE @ID INT, @IMPORTE MONEY, @OPERACION VARCHAR(15);
	DECLARE @CANTINSERT INT, @CANTDELETE INT;
	DECLARE @CURSOR1 CURSOR;

	IF NOT EXISTS (SELECT * FROM BITACORAS.sys.OBJECTS WHERE TYPE = 'U' AND NAME = 'BITACORA_PRESTAMOS')
	BEGIN
		CREATE TABLE BITACORAS.DBO.BITACORA_PRESTAMOS(
			TABLA VARCHAR(30),
			OPERACION VARCHAR(15),
			ID INT,
			IMPORTE MONEY,
			DESCIMPORTE VARCHAR(30)
		);
	END

	SET @CANTINSERT = (SELECT COUNT(*) FROM inserted);
	SET @CANTDELETE = (SELECT COUNT(*) FROM deleted);

	--UPDATE
	IF (@CANTINSERT > 0 AND @CANTDELETE > 0)
	BEGIN
		
		SET @OPERACION = 'UPDATE';
		SET @CURSOR1 = CURSOR FOR SELECT PREID, PREIMPORTE FROM deleted;
	END
	ELSE
	BEGIN
		IF (@CANTINSERT >0 AND @CANTDELETE = 0)
		BEGIN
			SET @OPERACION = 'INSERT';
			SET @CURSOR1 = CURSOR FOR SELECT PREID, PREIMPORTE FROM inserted;
		END
	ELSE
	BEGIN
		SET @OPERACION = 'DELETE';
		SET @CURSOR1 = CURSOR FOR SELECT PREID, PREIMPORTE FROM deleted;
	END --FIN CUANDO FUE DELETE
	END

	--ABRIR CURSOR
	OPEN @CURSOR1;

	--POSICIONARNOS AL PRIMER REGISTRO
	FETCH FROM @CURSOR1 INTO @ID, @IMPORTE;

	WHILE (@@FETCH_STATUS = 0)
	BEGIN

		INSERT INTO BITACORAS.DBO.BITACORA_PRESTAMOS VALUES
		('PRESTAMOS', @OPERACION, @ID, @IMPORTE, 'PREIMPORTE');
		
		--MOVER AL SIGUIENTE REGISTRO
		FETCH NEXT FROM @CURSOR1 INTO @ID, @IMPORTE;
	END --FIN WHILE

	--CERRA EL CURSOR
	CLOSE @CURSOR1;
	--LIBERAR
	DEALLOCATE @CURSOR1;

END

--***********PROBAMOS EL TRIGGER**********--

UPDATE PRESTAMOS
SET PREIMPORTE = 400
WHERE PREID IN (1, 2, 3);

--VERIFICAR QUE SE REGISTRO EN LA BITACORA
SELECT * FROM BITACORAS.DBO.BITACORA_PRESTAMOS;