--PRACTICA 6
--AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
--NO. CONTROL: 19400595
--FECHA: 17/05/22
--DESCRIPCION: Practicar la creacion de triggers y cursores

--PONER EN USO LA BD
USE HeroesDelMundo;

--CREAR EL TRIGGER
CREATE TRIGGER TR_DELETE_HEROES ON HEROES FOR DELETE
AS
BEGIN
--SENTENCIAS
SET NOCOUNT ON;

DECLARE @ID INT;
DECLARE @APODO VARCHAR(30);
DECLARE @ESTRELLAS TINYINT;

DECLARE @CHEROES CURSOR; 

IF NOT EXISTS (SELECT * FROM BITACORAS.sys.OBJECTS WHERE TYPE = 'U' AND NAME = 'HEROEBIT')
BEGIN
	CREATE TABLE BITACORAS.DBO.HEROEBIT(
		IDHEROE INT,
		APODO VARCHAR(30),
		ESTRELLAS TINYINT,
		USUARIO VARCHAR(30),
		PCORIGEN VARCHAR(200),
		FECHABORRADO DATE
	);
END

--INICIALIZAR EL CURSOR
SET @CHEROES = CURSOR FOR SELECT HER_ID, HER_ALIAS, HER_ESTRELLAS FROM deleted;

--ABRIR EL CURSOR
OPEN @CHEROES;

--POSICIONARNOS AL PRIMER REGISTRO
FETCH FROM @CHEROES INTO @ID, @APODO, @ESTRELLAS

--EMPEZAMOS CICLO; 0 SI LO PUDO LEER, 1 SI NO PUDO LEERLO
WHILE (@@FETCH_STATUS = 0)
BEGIN INSERT INTO BITACORAS.DBO.HEROEBIT
VALUES (@ID, @APODO, @ESTRELLAS, USER_NAME(), HOST_NAME(), GETDATE())
--MOVER AL SIGUIENTE REGISTRO
FETCH NEXT FROM @CHEROES INTO @ID, @APODO, @ESTRELLAS

END --FIN WHILE

CLOSE @CHEROES;
--LIBERAR
DEALLOCATE @CHEROES

END --FIN TRIGGER
GO

--HACER QUE EL TRIGGER SEA DISPARADO
DELETE FROM HEROES WHERE HER_ID IN (1011, 1012);

--VERIFICAR LA BITACORA
SELECT * FROM BITACORAS.DBO.HEROEBIT;