--PUBLICADOR

--CREAR VISTA PARA LA TABLA DE AUTOS
CREATE VIEW vista_Autos AS
(
SELECT Marca, Color, Precio, Anio, Modelo FROM AUTOS
);

--CREAR VISTA PARA LA TABLA DE CATEGORIA
CREATE VIEW vista_Categoria AS
(
SELECT NombreCategoria, Descripcion, ID FROM CATEGORIA
);

--SUSCRIPTOR

--VERIFICA QUE TE APAREZCAN TODOS LOS ARTÍCULOS.
SELECT * FROM AUTOS;
SELECT * FROM vista_Autos;
SELECT * FROM Categoria;
SELECT * FROM vista_Categoria;

--INGRESA 5 DATOS A LA TABLA AUTOS DESDE EL SUSCRIPTOR CREADO ANTERIORMENTE
INSERT INTO AUTOS (Marca, Modelo, Color, Anio, Precio) VALUES
('Nissan', '370z', 'Vino', 2013, '150000')
GO 5