/********************************\
		    ESPEJO
*********************************/

USE master;

-- Crear MASTER KEY del servidor espejo
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'abd';

-- Creamos un certificado para el servidor espejo
CREATE CERTIFICATE CESPEJO WITH SUBJECT = 'CERTIFICADO ESPEJO',
START_DATE = '2022-05-29 17:30:000';

-- Y para finalizar hacemos un backup del certificado el cual vamos a mover al servidor principal y el espejo
BACKUP CERTIFICATE CESPEJO TO FILE = 'C:\ABD2022\U5\Certificado\ESPEJO.cer';

--Creamos una puerta (un endpoint) para que el servidor espejo se pueda comunicar a traves del puerto 5022
CREATE ENDPOINT EPOINT
STATE = STARTED
AS TCP (LISTENER_PORT=5022, LISTENER_IP = ALL) 
FOR DATABASE_MIRRORING (AUTHENTICATION = CERTIFICATE CESPEJO, ENCRYPTION = REQUIRED ALGORITHM AES, ROLE = ALL);

--CREAMOS LOS USUARIOS y LOGINS
CREATE LOGIN PRINCIPAL WITH PASSWORD = 'abd';
CREATE USER UPRINCIPAL FOR LOGIN PRINCIPAL;

CREATE LOGIN ESPEJO WITH PASSWORD = 'abd';
CREATE USER UESPEJO FOR LOGIN ESPEJO;

CREATE LOGIN TESTIGO WITH PASSWORD = 'abd';
CREATE USER UTESTIGO FOR LOGIN TESTIGO;

-- Creamos el certificado de la base de datos de mirroring con los certificados de los otros servidores
--poniéndole como propietario los usuario recién creado. 
CREATE CERTIFICATE CPRIN AUTHORIZATION UPRINCIPAL FROM FILE = 'C:\ABD2022\U5\Certificado\CPRINCIPAL.cer';

CREATE CERTIFICATE CTEST AUTHORIZATION UTESTIGO FROM FILE = 'C:\ABD2022\U5\Certificado\TESTIGO.cer';

-- Le damos permisos a los usuario para conectarse al EndPoint
GRANT CONNECT ON ENDPOINT::EPOINT TO [PRINCIPAL];
GO
GRANT CONNECT ON ENDPOINT::EPOINT TO [ESPEJO];
GO
GRANT CONNECT ON ENDPOINT::EPOINT TO [TESTIGO];
GO

-- Restauramos las base de datos y el log en modo NO RECOVERY
RESTORE FILELISTONLY
FROM DISK = 'C:\ABD2022\U5\Certificado\SUPERMERCADO.BAK';

RESTORE DATABASE SUPERMERCADO FROM DISK='C:\ABD2022\U5\Certificado\SUPERMERCADO.BAK' WITH NORECOVERY,
MOVE 'SUPERMERCADO.MDF' TO 'C:\ABD2022\U5\Certificado\SUPERMERCADO.MDF',
MOVE 'SUPERMERCADO.LDF' TO 'C:\ABD2022\U5\Certificado\SUPERMERCADO.LDF'
GO
RESTORE LOG SUPERMERCADO FROM DISK='C:\ABD2022\U5\Certificado\SUPERMERCADO_LOG.BAK' WITH NORECOVERY
GO

ALTER DATABASE SUPERMERCADO SET PARTNER = 'TCP://192.168.0.101:5022';

--////////ELIMINACION DE OBJETOS ///////////////

ALTER DATABASE SUPERMERCADO SET PARTNER OFF;

DROP ENDPOINT epoint;

DROP CERTIFICATE CESPEJO;
DROP CERTIFICATE CPRIN;
DROP CERTIFICATE CESP;
DROP CERTIFICATE CTEST;

DROP MASTER KEY;

DROP USER UPRINCIPAL;
DROP USER UESPEJO;
DROP USER UTESTIGO;

DROP LOGIN PRINCIPAL;
DROP LOGIN TESTIGO;
DROP LOGIN ESPEJO;

--Hacer que el server falle
USE MASTER;
ALTER DATABASE SUPERMERCADO SET PARTNER FAILOVER

--ver certificados,Endpoint
SELECT * FROM sys.CERTIFICATES
SELECT * from sys.endpoints