--ESPEJO


--PONER EN USO MASTER
USE master;

--CREAR LA LLAVE MAESTRA
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'ABD';

--CREAR EL CERTIFICADO
CREATE CERTIFICATE CESPEJO WITH SUBJECT = 'CERTIFICATE ESPEJO',
START_DATE = '2022-06-06';

--CREAR BACKUP DLE CERTIFICADO
BACKUP CERTIFICATE CESPEJO TO FILE = 'C:\ABD2022\U5\Certificado\PRACTICA 9\CESPEJO.CER';

--CREAR EL ENPOINT
CREATE ENDPOINT EPOINT
STATE = STARTED AS TCP(LISTENER_PORT = 5024, LISTENER_IP = ALL) 
FOR DATABASE_MIRRORING
(AUTHENTICATION = CERTIFICATE CESPEJO, ENCRYPTION = REQUIRED ALGORITHM AES, ROLE = ALL);

--CREAR USUARIO Y LOGIN
CREATE LOGIN PRINCIPAL WITH PASSWORD = 'abd';
CREATE USER UPRINCIPAL FOR LOGIN PRINCIPAL;

CREATE LOGIN ESPEJO WITH PASSWORD = 'abd';
CREATE USER UESPEJO FOR LOGIN ESPEJO;

CREATE LOGIN TESTIGO WITH PASSWORD = 'abd';
CREATE USER UTESTIGO FOR LOGIN TESTIGO;

--CREAMOS EL CERTIFICADO DE LA BD MIRRORING, PONIENDO COMO PROPIETARIO EL USUARIO CORRESPONDIENTE

CREATE CERTIFICATE CPRIN AUTHORIZATION UPRINCIPAL FROM FILE = 'C:\ABD2022\U5\Certificado\PRACTICA 9\CPRINCIPAL.CER';

CREATE CERTIFICATE CTEST AUTHORIZATION UTESTIGO FROM FILE = 'C:\ABD2022\U5\Certificado\PRACTICA 9\TESTIGO.CER';

ALTER AUTHORIZATION ON CERTIFICATE :: CESPEJO TO UESPEJO;

--DAMOS PERMISO AL USUARIO PARA CONECTARSE AL ENDPOINT
GRANT CONNECT ON ENDPOINT::EPOINT TO [PRINCIPAL];
GRANT CONNECT ON ENDPOINT::EPOINT TO [ESPEJO];
GRANT CONNECT ON ENDPOINT::EPOINT TO [TESTIGO];

--RESTAURAR LA BD
RESTORE DATABASE ZOOLOGICO
FROM DISK = 'C:\ABD2022\U5\Certificado\PRACTICA 9\ZOOLOGICO.BAK'
WITH
MOVE 'ZOOLOGICO'
TO 'C:\ABD2022\U5\Certificado\PRACTICA 9\ZOOLOGICO.MDF',
MOVE 'ZOOLOGICO_LOG'
TO 'C:\ABD2022\U5\Certificado\PRACTICA 9\ZOOLOGICO.LDF',
REPLACE, NORECOVERY;

RESTORE LOG ZOOLOGICO
FROM DISK = 'C:\ABD2022\U5\Certificado\PRACTICA 9\ZOOLOGICO.TRN'
WITH
MOVE 'ZOOLOGICO'
TO 'C:\ABD2022\U5\Certificado\PRACTICA 9\ZOOLOGICO.MDF',
MOVE 'ZOOLOGICO_LOG'
TO 'C:\ABD2022\U5\Certificado\PRACTICA 9\ZOOLOGICO.LDF',
REPLACE, NORECOVERY;

--CONECTARSE CON EL SERVIDOR PRINCIPAL
ALTER DATABASE ZOOLOGICO SET PARTNER = 'TCP://192.168.0.2:5024';