--CREAR LA LLAVE MAESTRA
USE master;
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'abd';
GO

-- 4.
-- Creamos un certificado
CREATE CERTIFICATE CTESTIGO2 WITH SUBJECT = 'CERTIFICADO TESTIGO'
,START_DATE = '2022-05-26 13:00:000'
GO

-- 5.
-- Y para finalizar hacemos un backup del certificado.
BACKUP CERTIFICATE CTESTIGO2 TO FILE = 'C:\ABD2022\U5\Certificado\TESTIGO2.cer';
GO

-- 7.CREAR EL END POINT
CREATE ENDPOINT EPOINT2
   STATE = STARTED
   AS TCP (LISTENER_PORT=5023, LISTENER_IP = ALL) 
   FOR DATABASE_MIRRORING (AUTHENTICATION = CERTIFICATE CTESTIGO2, ENCRYPTION = REQUIRED ALGORITHM AES, ROLE = WITNESS);
GO

-- 8.CREAR USER AND LOGINS

CREATE LOGIN PRINCIPAL WITH PASSWORD = 'abd';
GO
CREATE USER UPRINCIPAL FOR LOGIN PRINCIPAL;
GO
CREATE LOGIN ESPEJO WITH PASSWORD = 'abd';
GO
CREATE USER UESPEJO FOR LOGIN ESPEJO;
GO
CREATE LOGIN TESTIGO WITH PASSWORD = 'abd';
GO
CREATE USER UTESTIGO FOR LOGIN TESTIGO
GO

-- 9.
-- Creamos el certificado de la base de datos de mirroring, poniéndole como propietario el usuario recién creado. 
CREATE CERTIFICATE CPRIN AUTHORIZATION UPRINCIPAL FROM FILE = 'C:\ABD2022\U5\Certificado\CPRINCIPAL2.cer'
GO
CREATE CERTIFICATE CESP AUTHORIZATION UESPEJO FROM FILE = 'C:\ABD2022\U5\Certificado\ESPEJO2.cer'
GO

-- 10.
-- Le damos permisos al usuario para conectarse al EndPoint
GRANT CONNECT ON ENDPOINT::EPOINT2 TO [PRINCIPAL];
GO
GRANT CONNECT ON ENDPOINT::EPOINT2 TO [ESPEJO];
GO
GRANT CONNECT ON ENDPOINT::EPOINT2 TO [TESTIGO];
GO